server {
    listen 80;
    server_name _;

    root /var/www/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location = /api.php {
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME /var/www/html/api.php;
        fastcgi_pass himnario-php:9000;
    }
}
